services:
  web:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      PORT: ${PORT_WEB:-80}
    ports:
      - "${HOST_PORT_WEB:-8080}:${PORT_WEB:-80}"
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      PORT: ${PORT_API:-8000}
    ports:
      - "${HOST_PORT_API:-8001}:${PORT_API:-8000}"
